"""
Diagnostic script to check PythonAnywhere deployment status
Run this locally, then provide commands to run on PythonAnywhere
"""

print("=" * 70)
print("PYTHONANYWHERE DIAGNOSTIC COMMANDS")
print("=" * 70)
print()
print("SSH into PythonAnywhere and run these commands:")
print()
print("1. Check current code version:")
print("   cd /home/bareeqalyusr/bareq-alyusr--3.0-")
print("   git log -1 --oneline")
print("   git status")
print()
print("2. Check if startup event is still in main.py:")
print("   grep -n '@app.on_event' /home/bareeqalyusr/bareq-alyusr--3.0-/app/main.py")
print("   # Should return nothing if fix is applied")
print()
print("3. Check WSGI file configuration:")
print("   cat /var/www/bareeqalyusr_pythonanywhere_com_wsgi.py")
print()
print("4. Check virtualenv packages:")
print("   /home/bareeqalyusr/bareq-alyusr--3.0-/venv/bin/pip list | grep -E '(fastapi|a2wsgi|uvicorn)'")
print()
print("5. Test if init_db() hangs:")
print("   cd /home/bareeqalyusr/bareq-alyusr--3.0-")
print("   /home/bareeqalyusr/bareq-alyusr--3.0-/venv/bin/python -c 'from app.database import init_db; init_db(); print(\"DB init OK\")'")
print()
print("6. Test if app imports without hanging:")
print("   cd /home/bareeqalyusr/bareq-alyusr--3.0-")
print("   timeout 10 /home/bareeqalyusr/bareq-alyusr--3.0-/venv/bin/python -c 'from app.main import app; print(\"App import OK\")'")
print()
print("=" * 70)
